// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v5.29.2
// source: syncer.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MapUpdateReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MapType       uint32                 `protobuf:"varint,1,opt,name=MapType,proto3" json:"MapType,omitempty"`
	SentAt        int64                  `protobuf:"varint,2,opt,name=SentAt,proto3" json:"SentAt,omitempty"`
	Events        []*MapUpdateEvent      `protobuf:"bytes,3,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MapUpdateReq) Reset() {
	*x = MapUpdateReq{}
	mi := &file_syncer_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MapUpdateReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MapUpdateReq) ProtoMessage() {}

func (x *MapUpdateReq) ProtoReflect() protoreflect.Message {
	mi := &file_syncer_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MapUpdateReq.ProtoReflect.Descriptor instead.
func (*MapUpdateReq) Descriptor() ([]byte, []int) {
	return file_syncer_proto_rawDescGZIP(), []int{0}
}

func (x *MapUpdateReq) GetMapType() uint32 {
	if x != nil {
		return x.MapType
	}
	return 0
}

func (x *MapUpdateReq) GetSentAt() int64 {
	if x != nil {
		return x.SentAt
	}
	return 0
}

func (x *MapUpdateReq) GetEvents() []*MapUpdateEvent {
	if x != nil {
		return x.Events
	}
	return nil
}

type MapUpdateResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	UpdateLatency int64                  `protobuf:"varint,2,opt,name=UpdateLatency,proto3" json:"UpdateLatency,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MapUpdateResp) Reset() {
	*x = MapUpdateResp{}
	mi := &file_syncer_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MapUpdateResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MapUpdateResp) ProtoMessage() {}

func (x *MapUpdateResp) ProtoReflect() protoreflect.Message {
	mi := &file_syncer_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MapUpdateResp.ProtoReflect.Descriptor instead.
func (*MapUpdateResp) Descriptor() ([]byte, []int) {
	return file_syncer_proto_rawDescGZIP(), []int{1}
}

func (x *MapUpdateResp) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *MapUpdateResp) GetUpdateLatency() int64 {
	if x != nil {
		return x.UpdateLatency
	}
	return 0
}

type FullSyncReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MapType       uint32                 `protobuf:"varint,1,opt,name=MapType,proto3" json:"MapType,omitempty"`
	SentAt        int64                  `protobuf:"varint,2,opt,name=SentAt,proto3" json:"SentAt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FullSyncReq) Reset() {
	*x = FullSyncReq{}
	mi := &file_syncer_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FullSyncReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FullSyncReq) ProtoMessage() {}

func (x *FullSyncReq) ProtoReflect() protoreflect.Message {
	mi := &file_syncer_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FullSyncReq.ProtoReflect.Descriptor instead.
func (*FullSyncReq) Descriptor() ([]byte, []int) {
	return file_syncer_proto_rawDescGZIP(), []int{2}
}

func (x *FullSyncReq) GetMapType() uint32 {
	if x != nil {
		return x.MapType
	}
	return 0
}

func (x *FullSyncReq) GetSentAt() int64 {
	if x != nil {
		return x.SentAt
	}
	return 0
}

type FullSyncResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MapType       uint32                 `protobuf:"varint,1,opt,name=MapType,proto3" json:"MapType,omitempty"`
	Events        []*MapUpdateEvent      `protobuf:"bytes,2,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FullSyncResp) Reset() {
	*x = FullSyncResp{}
	mi := &file_syncer_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FullSyncResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FullSyncResp) ProtoMessage() {}

func (x *FullSyncResp) ProtoReflect() protoreflect.Message {
	mi := &file_syncer_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FullSyncResp.ProtoReflect.Descriptor instead.
func (*FullSyncResp) Descriptor() ([]byte, []int) {
	return file_syncer_proto_rawDescGZIP(), []int{3}
}

func (x *FullSyncResp) GetMapType() uint32 {
	if x != nil {
		return x.MapType
	}
	return 0
}

func (x *FullSyncResp) GetEvents() []*MapUpdateEvent {
	if x != nil {
		return x.Events
	}
	return nil
}

type MapUpdateEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           []byte                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         []byte                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Type          uint32                 `protobuf:"varint,3,opt,name=type,proto3" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MapUpdateEvent) Reset() {
	*x = MapUpdateEvent{}
	mi := &file_syncer_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MapUpdateEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MapUpdateEvent) ProtoMessage() {}

func (x *MapUpdateEvent) ProtoReflect() protoreflect.Message {
	mi := &file_syncer_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MapUpdateEvent.ProtoReflect.Descriptor instead.
func (*MapUpdateEvent) Descriptor() ([]byte, []int) {
	return file_syncer_proto_rawDescGZIP(), []int{4}
}

func (x *MapUpdateEvent) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *MapUpdateEvent) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *MapUpdateEvent) GetType() uint32 {
	if x != nil {
		return x.Type
	}
	return 0
}

var File_syncer_proto protoreflect.FileDescriptor

const file_syncer_proto_rawDesc = "" +
	"\n" +
	"\fsyncer.proto\x12\x06syncer\"p\n" +
	"\fMapUpdateReq\x12\x18\n" +
	"\aMapType\x18\x01 \x01(\rR\aMapType\x12\x16\n" +
	"\x06SentAt\x18\x02 \x01(\x03R\x06SentAt\x12.\n" +
	"\x06events\x18\x03 \x03(\v2\x16.syncer.MapUpdateEventR\x06events\"E\n" +
	"\rMapUpdateResp\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12$\n" +
	"\rUpdateLatency\x18\x02 \x01(\x03R\rUpdateLatency\"?\n" +
	"\vFullSyncReq\x12\x18\n" +
	"\aMapType\x18\x01 \x01(\rR\aMapType\x12\x16\n" +
	"\x06SentAt\x18\x02 \x01(\x03R\x06SentAt\"X\n" +
	"\fFullSyncResp\x12\x18\n" +
	"\aMapType\x18\x01 \x01(\rR\aMapType\x12.\n" +
	"\x06events\x18\x02 \x03(\v2\x16.syncer.MapUpdateEventR\x06events\"L\n" +
	"\x0eMapUpdateEvent\x12\x10\n" +
	"\x03key\x18\x01 \x01(\fR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value\x12\x12\n" +
	"\x04type\x18\x03 \x01(\rR\x04type2|\n" +
	"\x06Syncer\x12;\n" +
	"\fHandleUpdate\x12\x14.syncer.MapUpdateReq\x1a\x15.syncer.MapUpdateResp\x125\n" +
	"\bFullSync\x12\x13.syncer.FullSyncReq\x1a\x14.syncer.FullSyncRespB\x14Z\x12internal/syncer/pbb\x06proto3"

var (
	file_syncer_proto_rawDescOnce sync.Once
	file_syncer_proto_rawDescData []byte
)

func file_syncer_proto_rawDescGZIP() []byte {
	file_syncer_proto_rawDescOnce.Do(func() {
		file_syncer_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_syncer_proto_rawDesc), len(file_syncer_proto_rawDesc)))
	})
	return file_syncer_proto_rawDescData
}

var file_syncer_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_syncer_proto_goTypes = []any{
	(*MapUpdateReq)(nil),   // 0: syncer.MapUpdateReq
	(*MapUpdateResp)(nil),  // 1: syncer.MapUpdateResp
	(*FullSyncReq)(nil),    // 2: syncer.FullSyncReq
	(*FullSyncResp)(nil),   // 3: syncer.FullSyncResp
	(*MapUpdateEvent)(nil), // 4: syncer.MapUpdateEvent
}
var file_syncer_proto_depIdxs = []int32{
	4, // 0: syncer.MapUpdateReq.events:type_name -> syncer.MapUpdateEvent
	4, // 1: syncer.FullSyncResp.events:type_name -> syncer.MapUpdateEvent
	0, // 2: syncer.Syncer.HandleUpdate:input_type -> syncer.MapUpdateReq
	2, // 3: syncer.Syncer.FullSync:input_type -> syncer.FullSyncReq
	1, // 4: syncer.Syncer.HandleUpdate:output_type -> syncer.MapUpdateResp
	3, // 5: syncer.Syncer.FullSync:output_type -> syncer.FullSyncResp
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_syncer_proto_init() }
func file_syncer_proto_init() {
	if File_syncer_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_syncer_proto_rawDesc), len(file_syncer_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_syncer_proto_goTypes,
		DependencyIndexes: file_syncer_proto_depIdxs,
		MessageInfos:      file_syncer_proto_msgTypes,
	}.Build()
	File_syncer_proto = out.File
	file_syncer_proto_goTypes = nil
	file_syncer_proto_depIdxs = nil
}
