// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64

package bpfloader

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

type bpfloaderWatershedState struct{ HostPid uint32 }

// loadBpfloader returns the embedded CollectionSpec for bpfloader.
func loadBpfloader() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_BpfloaderBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load bpfloader: %w", err)
	}

	return spec, err
}

// loadBpfloaderObjects loads bpfloader and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*bpfloaderObjects
//	*bpfloaderPrograms
//	*bpfloaderMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadBpfloaderObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadBpfloader()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// bpfloaderSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfloaderSpecs struct {
	bpfloaderProgramSpecs
	bpfloaderMapSpecs
}

// bpfloaderSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfloaderProgramSpecs struct {
	BpfProgKernHtabLruUpdate *ebpf.ProgramSpec `ebpf:"bpf_prog_kern_htab_lru_update"`
}

// bpfloaderMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfloaderMapSpecs struct {
	EgressIpSet           *ebpf.MapSpec `ebpf:"egress_ip_set"`
	MapEventsSnatextPart0 *ebpf.MapSpec `ebpf:"map_events_snatext_part_0"`
	SnatEventsStat        *ebpf.MapSpec `ebpf:"snat_events_stat"`
	WsState               *ebpf.MapSpec `ebpf:"ws_state"`
}

// bpfloaderObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadBpfloaderObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfloaderObjects struct {
	bpfloaderPrograms
	bpfloaderMaps
}

func (o *bpfloaderObjects) Close() error {
	return _BpfloaderClose(
		&o.bpfloaderPrograms,
		&o.bpfloaderMaps,
	)
}

// bpfloaderMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadBpfloaderObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfloaderMaps struct {
	EgressIpSet           *ebpf.Map `ebpf:"egress_ip_set"`
	MapEventsSnatextPart0 *ebpf.Map `ebpf:"map_events_snatext_part_0"`
	SnatEventsStat        *ebpf.Map `ebpf:"snat_events_stat"`
	WsState               *ebpf.Map `ebpf:"ws_state"`
}

func (m *bpfloaderMaps) Close() error {
	return _BpfloaderClose(
		m.EgressIpSet,
		m.MapEventsSnatextPart0,
		m.SnatEventsStat,
		m.WsState,
	)
}

// bpfloaderPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadBpfloaderObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfloaderPrograms struct {
	BpfProgKernHtabLruUpdate *ebpf.Program `ebpf:"bpf_prog_kern_htab_lru_update"`
}

func (p *bpfloaderPrograms) Close() error {
	return _BpfloaderClose(
		p.BpfProgKernHtabLruUpdate,
	)
}

func _BpfloaderClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed bpfloader_x86_bpfel.o
var _BpfloaderBytes []byte
